### ISSUE TITLE
Questions about idl save files

### ISSUE THREAD

**Issue by opoplawski** [hsocasnavarro/NICOLE#1]
idlsave.py is shipped in the run/ directory, but is not found automatically by ./run_nicole.  I don't see any references to setting PYTHONPATH in the manual.  Any guidelines here?

Also, idlsave has been merged into Scipy 0.9.0 onwards. To use the version in scipy.io, import the read function with from scipy.io.idl import readsav and then use readsav as you would use idlsave.read.  Not sure you want to add a dep on scipy just for that though.

**Comment by hsocasnavarro** [comment]
Do you have idlsave.py in the same directory you are running? It is assumed that you have all the python tools in the run directory.

Thanks for the info about scipy. I guess I'll need to decide which dependence I want to have. I'd like to keep it to a minimum, of course

**Comment by opoplawski** [comment]
yes, but at least on RHEL6 and Fedora 20 - '.' is not in sys.path.
